### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by imanghafoori1**
Badges added

### CODE REVIEW

**Comment by nahid** [comment]
Thanks @imanghafoori1

**Comment by imanghafoori1** [comment]
You are welcome.
But why your build process is not passing on travis ?!

**Comment by imanghafoori1** [comment]
I also recommend you to you scrutinizer-ci.com to measure your code quality and more.
I am using it for my own package: 
github.com/imanghafoori1/laravel-widgetize

the code quality badge is generated from scrutinizer results.

**Comment by nahid** [comment]
Thank you for you suggestion. Insha'Allah I'll integrate scrutinizer-ci ASAP.

**Comment by imanghafoori1** [comment]
Insha'Allah 👍

**Pull request merged**
