### PR TITLE
ReceiverID parameter updated in sendMessageByUserId

### PR DESCRIPTION
**Pull request by sahasovon**
sendMessageByUserId function set sender & receiver both to authenticated user. Issue is fixed.

### CODE REVIEW

**Comment by nahid** [comment]
What the fucking changes you do man? 👎

**Comment by sahasovon** [comment]
First of all You Should Talk Properly. The 2nd commit was a mistake, not intentional. You should check the first commit.

**Comment by nahid** [comment]
Sorry for my language :)

**Comment by nahid** [comment]
Sorry for my language :)

**Pull request closed without merging**
