### PR TITLE
Update MessageRepository.php

### PR DESCRIPTION
**Pull request by imanghafoori1**
just simpler code

### CODE REVIEW

**Comment by cfpinto** [comment]
@imanghafoori1 can you trigger the build again? Last time it failed due to an HVVM issue

**Comment by cfpinto** [comment]
> I do not find any button to re-try.

Push a small change like a blockquote

**Comment by imanghafoori1** [comment]
Sorry I have deleted the source repo long ago
it is a small and safe to merge change.
Do not worry about it

**Comment by imanghafoori1** [comment]
Or you can close this and try it as your self

**Comment by cfpinto** [comment]
Ok. thank, will integrate your changes in future commit. Closing this one for now

**Pull request closed without merging**
